dist: trusty
sudo: required
language: node_js
node_js:
  "7"

env:
  GOPATH: $HOME/go
  PATH: $GOPATH/bin:$PATH

install:
  - pip3 install -r pip3-requirements.txt
  - pip2 install -r pip2-requirements.txt

script:
  - coala --ci
  - editorconfig-tools check **/*
